---
- name: playbook for file copying
  hosts: all
  become: true
  tasks:
    - name: copy a file
      copy:
        src: /home/ansadmin/ansible/index.html
        dest: /home/ansadmin
        mode: 0600
        owner: pam  
