---
- name: playbook to install httpd
  hosts: all
  become: true
  tasks:
    - name: install package
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

  
    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"


    - name: install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    - name: copying a file
      copy:
        src: /home/ansadmin/ansible/index.html
        dest: /var/www/html/
        mode: 0666
