---
- name: install httpd on ubuntu
  hosts: appservers
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start apache2 service
      service:
        name: apache2
        state: started

