---
- name: install httpd on ubuntu
  hosts: appservers
  become: yes
  tasks:
  
    - name: stop apache2 service
      service:
        name: apache2
        state: stopped
    - name: uninstall apache2
      apt:
         name: apache2
         state: absent


